---
python: '3.6'
language: cpp
jobs:
  include:
    - os: linux
      dist: xenial
      env: BUILD=linux
    - os: osx
      osx_image: xcode11.5
      env: BUILD=osx
    - os: linux
      dist: xenial
      env: BUILD=android
env:
  global:
    - secure: RNbJ4k1F1YVL9sgG5w77eK55S+pLIV9TTKGPTmcR+BKjFM5DX7FgLH9xsV60n3rXfwoMUizFO5/AoFrHr7h/F+HpPa5rR+3b61LAHTJ9wCB/nbmbmgqIhlzVcAjWy0kwiLZh1zCS4g/yr3q8uCbgRWhQBCGEciAeuS4PYjK8T8GazOS1ic4CeDDRbOUPFkjoLQzGj5tM7DkaAqORFau0gtKfnpK4Qfc4HMZy28kSq0d8BQSl9V6t0Yj6jtHcIxO9TJqdvHOKALDqWltisnzShHcOPvgn2aV1b3qKz/dl5tQaWDGQPcdkXiK5e67DOVoswEJ5fDKGC+ptIUJYU+e+7cnx51O2qdDAwGxCsozN+8DY/LMVspraMvDvC9kBTNM6hHXRcbv8GiISKigq+yjfSQ7WqNoWYEO18mgN/UcJT3HUI4j2EDj8ZTt73/6s6f/DrT4SU7grQVp0MNR6GD8e8prpY49vjZRaz1sTH/xIdKHNpVLnuUHz8+SEevFxCkA9+dywFu6TbamNZpRfg650VhQjiSSOKOwN5GmR1m92SQ8abkzFfedtlufdcwNOPdmA0/xmXizmZTbXXyRkDKfIccKVxiI2miSO4JTS0nUzufdHvH0Sx2/Jz3DBJVbWZU2Wpoq74AX+x0mJiWsldnbvKeNOJArsHB45+PbmgMNP/2k=
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-7
    packages:
      - g++-9
      - clang-7
      - clang-tidy-7
      - clang-format-7
      - libasound2-dev
      - libfreetype6-dev
      - libxcb-xkb-dev
      - libxcb-xinerama0-dev
      - libxcb-render-util0-dev
      - libxcb-icccm4-dev
      - libxcb-shm0-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libgl1-mesa-dev
      - libegl1-mesa-dev
      - libdbus-1-dev
      - libgtk-3-dev
      - libglib2.0-dev
  coverity_scan:
    project:
      name: lemourin/libcloudstorage
      description: Build submitted via Travis CI
    notification_email: pawel.wegner95@gmail.com
    build_command_prepend: cov-configure --comptype gcc --compiler gcc-9 --template && mkdir build-coverity && cd build-coverity && CXX=g++-9 CC=gcc-9 cmake .. -DCMAKE_PREFIX_PATH=$PWD/../contrib/x86_64-linux-gnu
    build_command: make -j 4
    branch_pattern: coverity

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - |
    if [ "$BUILD" = "linux" ]; then
      set -e
      for i in $(find test src bin examples -type f \( -regex '.*\.\(h\|cpp\|c\)$' ! -regex 'test/googletest/.*$' \)); do
        clang-format-7 $i | diff - $i > /dev/null
      done
      cd contrib
      wget -nc https://github.com/lemourin/libcloudstorage/releases/download/1.9/x86_64-linux-gnu.tar.gz
      tar xf x86_64-linux-gnu.tar.gz
      ./change-prefix.sh
      wget https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.sh
      chmod +x cmake-3.17.3-Linux-x86_64.sh
      ./cmake-3.17.3-Linux-x86_64.sh --skip-license --prefix=$PWD/x86_64-linux-gnu
      export PATH="$PWD/x86_64-linux-gnu/bin:$PATH"
      cd ..
    fi
  - |
    if [ "$BUILD" = "osx" ]; then
      cd contrib &&
      wget -nc https://github.com/lemourin/libcloudstorage/releases/download/1.9/x86_64-darwin-macos.tar.gz &&
      tar xf x86_64-darwin-macos.tar.gz &&
      sed -i.bak "s/x86_64-linux-gnu/x86_64-darwin-macos/g" change-prefix.sh &&
      ./change-prefix.sh &&
      cd ..
    fi
  - |
    if [ "$BUILD" = "android" ]; then
      mkdir AndroidSdk &&
      cd AndroidSdk &&
      export ANDROID_ABI=x86 &&
      export ANDROID_MIN_API_LEVEL=21 &&
      export ANDROID_HOME=$PWD &&
      export ANDROID_NDK_ROOT=$PWD/android-ndk-r21d &&
      wget -nc https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip &&
      unzip android-ndk-r21d-linux-x86_64.zip &&
      mkdir cmdline-tools &&
      cd cmdline-tools &&
      wget -nc https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip &&
      unzip commandlinetools-linux-6609375_latest.zip &&
      yes | ./tools/bin/sdkmanager "platforms;android-$ANDROID_MIN_API_LEVEL" &&
      cd ../.. &&
      cd contrib &&
      wget https://github.com/lemourin/libcloudstorage/releases/download/1.9/i686-linux-android$ANDROID_MIN_API_LEVEL.tar.gz &&
      tar xf i686-linux-android$ANDROID_MIN_API_LEVEL.tar.gz &&
      wget https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.sh &&
      chmod +x cmake-3.17.3-Linux-x86_64.sh &&
      ./cmake-3.17.3-Linux-x86_64.sh --skip-license --prefix=$PWD/i686-linux-android$ANDROID_MIN_API_LEVEL &&
      export PATH="$PWD/i686-linux-android$ANDROID_MIN_API_LEVEL/bin:$PATH" &&
      cd ..
    fi

script:
  - mkdir build
  - cd build
  - |
    if [ "$BUILD" = "linux" ]; then
      set -e
      export PKG_CONFIG_PATH=$PWD/../contrib/x86_64-linux-gnu/lib/pkgconfig
      CONTRIB_PATH=$PWD/../contrib/x86_64-linux-gnu/lib
      SYSTEM_PATH=/usr/lib/x86_64-linux-gnu
      CXXFLAGS="-Wall -Wextra -O2 -fsanitize=address"
      LDFLAGS="-static-libasan -fsanitize=address"
      CC=gcc-9
      CXX=g++-9
      cmake .. -DCMAKE_FIND_ROOT_PATH=$CONTRIB_PATH/../ -DBUILD_SHARED_LIBS=0 \
        -DCMAKE_BUILD_TYPE=Release \
        -Dcurl_LIBRARY="$CONTRIB_PATH/libcurl.a;$CONTRIB_PATH/libnghttp2.a;$CONTRIB_PATH/libssl.a;$CONTRIB_PATH/libcrypto.a;$CONTRIB_PATH/libcares.a;$CONTRIB_PATH/libz.a;$SYSTEM_PATH/libpthread.so;$SYSTEM_PATH/libdl.so" \
        -Dmpv_LIBRARY="$CONTRIB_PATH/libmpv.a;$CONTRIB_PATH/libass.a;$CONTRIB_PATH/libfribidi.a;$CONTRIB_PATH/libavdevice.a;$SYSTEM_PATH/libasound.so;$SYSTEM_PATH/libXinerama.so;$SYSTEM_PATH/libXss.so;$SYSTEM_PATH/libXrandr.so" \
        -Davformat_LIBRARY="$CONTRIB_PATH/libavformat.a;$CONTRIB_PATH/libxml2.a;$CONTRIB_PATH/libz.a;$CONTRIB_PATH/libssl.a;$CONTRIB_PATH/libcrypto.a" \
        -Davfilter_LIBRARY="$CONTRIB_PATH/libavfilter.a;$CONTRIB_PATH/libass.a;$CONTRIB_PATH/libharfbuzz.a;$SYSTEM_PATH/libfreetype.so;$CONTRIB_PATH/libfribidi.a;$SYSTEM_PATH/libfontconfig.so;$CONTRIB_PATH/libz.a;" \
        -Davcodec_LIBRARY="$CONTRIB_PATH/libavcodec.a;$CONTRIB_PATH/libz.a" \
        -Dmega_LIBRARY="$CONTRIB_PATH/libmega.a;$CONTRIB_PATH/libcryptopp.a" \
        -DCMAKE_EXE_LINKER_FLAGS="-static-libstdc++ -static-libgcc"
      make -j 4
      make test CXXFLAGS=-Wno-sign-compare -j 4
      strip bin/cloudbrowser/cloudbrowser
      mv bin/cloudbrowser/cloudbrowser bin/cloudbrowser/cloudbrowser-linux
      cd ..
      clang-tidy-7 $(find src bin test examples -name "*.cpp") -- \
        -Isrc -Ibin/cloudbrowser/src -Itest $(pkg-config --cflags jsoncpp Qt5Quick fuse3) \
        -Itest/googletest/googletest/include \
        -Itest/googletest/googlemock/include \
        -Ibuild/src \
        -DWITH_FUSE -DWITH_MPV -DWITH_CURL -DWITH_MICROHTTPD -DWITH_THUMBNAILER -DWITH_CRYPTOPP -fPIC
    fi
  - |
    if [ "$BUILD" = "osx" ]; then
      export PKG_CONFIG_LIBDIR=$PWD/../contrib/x86_64-darwin-macos/lib/pkgconfig &&
      CONTRIB_PATH=$PWD/../contrib/x86_64-darwin-macos/lib &&
      cmake .. -DCMAKE_FIND_ROOT_PATH=$CONTRIB_PATH/../ -DBUILD_SHARED_LIBS=0 \
        -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 \
        -DCMAKE_BUILD_TYPE=Release \
        -Dcurl_LIBRARY="$CONTRIB_PATH/libcurl.a;$CONTRIB_PATH/libnghttp2.a;$CONTRIB_PATH/libssl.a;$CONTRIB_PATH/libcrypto.a;$CONTRIB_PATH/libcares.a;$CONTRIB_PATH/libz.a;" \
        -Dmega_LIBRARY="$CONTRIB_PATH/libmega.a;$CONTRIB_PATH/libcryptopp.a;" \
        -Davcodec_LIBRARY="$CONTRIB_PATH/libavcodec.a;$CONTRIB_PATH/libz.a;/usr/lib/libiconv.dylib" \
        -Davformat_LIBRARY="$CONTRIB_PATH/libavformat.a;$CONTRIB_PATH/libxml2.a;$CONTRIB_PATH/libz.a;$CONTRIB_PATH/libssl.a;$CONTRIB_PATH/libcrypto.a;" \
        -Davfilter_LIBRARY="$CONTRIB_PATH/libavfilter.a;$CONTRIB_PATH/libass.a;$CONTRIB_PATH/libharfbuzz.a;$CONTRIB_PATH/libfreetype.a;$CONTRIB_PATH/libfribidi.a;$CONTRIB_PATH/libz.a;" \
        -Dmpv_LIBRARY="$CONTRIB_PATH/libmpv.a;$CONTRIB_PATH/libass.a;$CONTRIB_PATH/libfribidi.a;$CONTRIB_PATH/libavdevice.a;" \
        -DCMAKE_EXE_LINKER_FLAGS=" \
          -framework Foundation \
          -framework SystemConfiguration \
          -framework AudioToolbox \
          -framework VideoToolbox \
          -framework CoreMedia \
          -framework CoreAudio \
          -framework AVFoundation \
          -framework CoreVideo \
          -framework CoreGraphics \
          -framework CoreText \
          -framework CoreImage \
          -framework OpenGL \
          -framework AppKit \
        " &&
      make -j 4 &&
      make -j 4 test &&
      strip bin/cloudbrowser/cloudbrowser &&
      cd bin/cloudbrowser &&
      mkdir -p "Cloud Browser.app/Contents/MacOS" &&
      mkdir -p "Cloud Browser.app/Contents/Resources" &&
      brew install makeicns &&
      makeicns -in ../../../bin/cloudbrowser/resources/cloud.png -out "Cloud Browser.app/Contents/Resources/cloud.icns" &&
      mv cloudbrowser "Cloud Browser.app/Contents/MacOS" &&
      cat > "Cloud Browser.app/Contents/Info.plist" << EOF
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
      <dict>
        <key>CFBundleExecutable</key>
        <string>cloudbrowser</string>
        <key>CFBundleIdentifier</key>
        <string>org.videolan.cloudbrowser</string>
        <key>CFBundleName</key>
        <string>Cloud Browser</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>CFBundleIconFile</key>
        <string>cloud</string>
      </dict>
    </plist>
    EOF
      [ $? -eq 0 ] &&
      brew install graphicsmagick imagemagick &&
      npm install create-dmg -g &&
      create-dmg "Cloud Browser.app" || true &&
      mv "Cloud Browser Undefined.dmg" cloudbrowser.dmg &&
      cd ../../../
    fi
  - |
    if [ "$BUILD" = "android" ]; then
      CONTRIB_PATH=$PWD/../contrib/i686-linux-android$ANDROID_MIN_API_LEVEL/lib
      SYSTEM_PATH=$ANDROID_NDK_ROOT/platforms/android-$ANDROID_MIN_API_LEVEL/arch-$ANDROID_ABI/usr/lib
      cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_FIND_ROOT_PATH=$CONTRIB_PATH/.. \
          -DQt5Core_DIR=$CONTRIB_PATH/cmake/Qt5Core \
          -DQt5Quick_DIR=$CONTRIB_PATH/cmake/Qt5Quick \
          -DQt5Gui_DIR=$CONTRIB_PATH/cmake/Qt5Gui \
          -DQt5QmlModels_DIR=$CONTRIB_PATH/cmake/Qt5QmlModels \
          -DQt5Qml_DIR=$CONTRIB_PATH/cmake/Qt5Qml \
          -DQt5Network_DIR=$CONTRIB_PATH/cmake/Qt5Network \
          -DQt5Widgets_DIR=$CONTRIB_PATH/cmake/Qt5Widgets \
          -DQt5Svg_DIR=$CONTRIB_PATH/cmake/Qt5Svg \
          -DQt5AndroidExtras_DIR=$CONTRIB_PATH/cmake/Qt5AndroidExtras \
          -DQt5QuickControls2_DIR=$CONTRIB_PATH/cmake/Qt5QuickControls2 \
          -DQt5QmlWorkerScript_DIR=$CONTRIB_PATH/cmake/Qt5QmlWorkerScript \
          -DQt5WebView_FOUND=FALSE \
          -Dkirigami_plugin_LIBRARY=$CONTRIB_PATH/../qml/org/kde/kirigami.2/libkirigamiplugin.a \
          -Dqtgraphicaleffects_plugin_LIBRARY=$CONTRIB_PATH/../qml/QtGraphicalEffects/libqml_QtGraphicalEffects_qtgraphicaleffectsplugin_$ANDROID_ABI.a \
          -Dqtgraphicaleffectsprivate_plugin_LIBRARY=$CONTRIB_PATH/../qml/QtGraphicalEffects/private/libqml_QtGraphicalEffects_private_qtgraphicaleffectsprivate_$ANDROID_ABI.a \
          -Dqtlabsplatform_plugin_LIBRARY=$CONTRIB_PATH/../qml/Qt/labs/platform/libqml_Qt_labs_platform_qtlabsplatformplugin_$ANDROID_ABI.a \
          -Dqtqmlmodels_plugin_LIBRARY="$CONTRIB_PATH/../qml/QtQml/Models.2/libqml_QtQml_Models.2_modelsplugin_$ANDROID_ABI.a;$CONTRIB_PATH/../qml/QtQml/libqml_QtQml_qmlplugin_$ANDROID_ABI.a"\
          -Dqtquick2_plugin_LIBRARY=$CONTRIB_PATH/../qml/QtQuick.2/libqml_QtQuick.2_qtquick2plugin_$ANDROID_ABI.a \
          -Dqtquickcontrols2_plugin_LIBRARY=$CONTRIB_PATH/../qml/QtQuick/Controls.2/libqml_QtQuick_Controls.2_qtquickcontrols2plugin_$ANDROID_ABI.a \
          -Dqtquickcontrols2materialstyle_plugin_LIBRARY=$CONTRIB_PATH/../qml/QtQuick/Controls.2/Material/libqml_QtQuick_Controls.2_Material_qtquickcontrols2materialstyleplugin_$ANDROID_ABI.a \
          -Dqtquicklayouts_plugin_LIBRARY=$CONTRIB_PATH/../qml/QtQuick/Layouts/libqml_QtQuick_Layouts_qquicklayoutsplugin_$ANDROID_ABI.a \
          -Dqtquicktemplates2_plugin_LIBRARY=$CONTRIB_PATH/../qml/QtQuick/Templates.2/libqml_QtQuick_Templates.2_qtquicktemplates2plugin_$ANDROID_ABI.a \
          -Dqtsvg_plugin_LIBRARY=$CONTRIB_PATH/../plugins/imageformats/libplugins_imageformats_qsvg_$ANDROID_ABI.a \
          -Dqtsvgicon_plugin_LIBRARY=$CONTRIB_PATH/../plugins/iconengines/libplugins_iconengines_qsvgicon_$ANDROID_ABI.a \
          -Dqtwindow_plugin_LIBRARY=$CONTRIB_PATH/../qml/QtQuick/Window.2/libqml_QtQuick_Window.2_windowplugin_$ANDROID_ABI.a \
          -Dcurl_LIBRARY="$CONTRIB_PATH/libcurl.a;$CONTRIB_PATH/libssl.a;$CONTRIB_PATH/libcrypto.a;$CONTRIB_PATH/libnghttp2.a;$CONTRIB_PATH/libcares.a;$SYSTEM_PATH/libz.a" \
          -Dmega_LIBRARY="$CONTRIB_PATH/libmega.a;$CONTRIB_PATH/libcryptopp.a" \
          -Dmpv_LIBRARY="$CONTRIB_PATH/libmpv.a;$CONTRIB_PATH/libass.a;$CONTRIB_PATH/libharfbuzz.a;$CONTRIB_PATH/libfribidi.a;$SYSTEM_PATH/libOpenSLES.so" \
          -Davcodec_LIBRARY="$CONTRIB_PATH/libavcodec.a;$SYSTEM_PATH/libz.a" \
          -DBUILD_SHARED_LIBS=0 \
          -DBUILD_TESTING=0 \
          -DCMAKE_CXX_FLAGS="-fPIC" \
          -DCMAKE_C_FLAGS="-fPIC" \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=$ANDROID_ABI \
          -DANDROID_NATIVE_API_LEVEL=$ANDROID_MIN_API_LEVEL &&
      make -j 4
    fi

deploy:
  - provider: releases
    overwrite: true
    api_key:
      secure: FKvjbAn/91TRlQMOYO3Bsfx3IYe+BEAkjS/EGfEiR7WKh0Xz2c6HzDucKuNq0MuPPh8ddQO+szVWwSJXMG2brXQtKuRPdPARGLOiR3R8+F2UAnQ6o3AVoXcpZCVYgqZzg4gz8I7+LhL+48UKhNykU4DT3ahtL9kAmMmBbI4sl84WEwSxw7QHMKD8y/fVskyBYOzg1uT1sbmiupy0oErJyi+s8faYLcVPmremWZeJL5pra76+xjO9siriIscOKPONknKu7w2s7AeVHdW4VEmkc4iLVUpz0xsUWaoIaX16smkVtz3pE34UBigO1JyJPqYO+c2CNDqXOJwN+xx1GIqL65vColrZB9IkRdfa0chmIy6c05ZvDpyZtNwOBqImBx6kod34URpz+kwwKK+9a56HcDrXYUZ+Knmcm/4t6LSH51QksjLLxqnI2wqDvmohUkyo3cZfPw8bBB0c7NRwVDNStQLxKnsXfZ8H58uYd3XhERGn2/D13JX0VvRb8lUMwSWsLADng1oLfe8ITiD46NzdUwOCgcS3NYlM51l8q6D00QMlzCqDGJeFI/lFR2a4o5xhXYkx3Dn5cAj6D1i+O0WLSDLOP7ILIuNKP5E5msTvvpuslaUMM/oEwLl0WnVkRpSKSxLBAi5bQL3xQo64PO9oCvnC/37sa/0NCdfiI99nXfE=
    file: "build/bin/cloudbrowser/cloudbrowser-linux"
    skip_cleanup: true
    on:
      tags: true
      condition: $BUILD = linux
  - provider: releases
    overwrite: true
    api_key:
      secure: FKvjbAn/91TRlQMOYO3Bsfx3IYe+BEAkjS/EGfEiR7WKh0Xz2c6HzDucKuNq0MuPPh8ddQO+szVWwSJXMG2brXQtKuRPdPARGLOiR3R8+F2UAnQ6o3AVoXcpZCVYgqZzg4gz8I7+LhL+48UKhNykU4DT3ahtL9kAmMmBbI4sl84WEwSxw7QHMKD8y/fVskyBYOzg1uT1sbmiupy0oErJyi+s8faYLcVPmremWZeJL5pra76+xjO9siriIscOKPONknKu7w2s7AeVHdW4VEmkc4iLVUpz0xsUWaoIaX16smkVtz3pE34UBigO1JyJPqYO+c2CNDqXOJwN+xx1GIqL65vColrZB9IkRdfa0chmIy6c05ZvDpyZtNwOBqImBx6kod34URpz+kwwKK+9a56HcDrXYUZ+Knmcm/4t6LSH51QksjLLxqnI2wqDvmohUkyo3cZfPw8bBB0c7NRwVDNStQLxKnsXfZ8H58uYd3XhERGn2/D13JX0VvRb8lUMwSWsLADng1oLfe8ITiD46NzdUwOCgcS3NYlM51l8q6D00QMlzCqDGJeFI/lFR2a4o5xhXYkx3Dn5cAj6D1i+O0WLSDLOP7ILIuNKP5E5msTvvpuslaUMM/oEwLl0WnVkRpSKSxLBAi5bQL3xQo64PO9oCvnC/37sa/0NCdfiI99nXfE=
    file: "build/bin/cloudbrowser/cloudbrowser.dmg"
    skip_cleanup: true
    on:
      tags: true
      condition: $BUILD = osx
